DEBUG:root:received {"dest":"n5","body":{"type":"init","node_id":"n5","node_ids":["n1","n2","n3","n4","n5"],"msg_id":1},"src":"c0","id":0}
INFO:root:node n5 initialized
DEBUG:root:sending {"dest": "c0", "src": "n5", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
INFO:root:node
n1
current time
1651669902091577668
node_time
1651669902091570873
dif
6795
True

INFO:root:leader alive, resuming timeout checker

DEBUG:root:received {"dest":"n5","src":"n1","body":{"msg_id":5,"type":"AppendEntries","term":0,"prevIndex":0,"prevTerm":0,"entries":[],"commit":0},"id":16}
DEBUG:root:received {"dest":"n5","src":"n2","body":{"msg_id":6,"type":"RequestVote","term":1,"prevLogIndex":0,"lastLogTerm":0,"candidateId":"n2"},"id":17}
DEBUG:root:sending {"dest": "n1", "src": "n5", "body": {"msg_id": 2, "in_reply_to": 5, "type": "AppendEntriesRes", "res": true, "term": 0, "next": 1, "commit": 0}}
DEBUG:root:sending {"dest": "n2", "src": "n5", "body": {"msg_id": 3, "in_reply_to": 6, "type": "RequestVoteRes", "term": 1, "res": true}}
INFO:root:election started and voted vor
n2
at time
1651669902101866685

DEBUG:root:received {"dest":"n5","src":"n2","body":{"msg_id":12,"type":"AppendEntries","term":1,"prevIndex":0,"prevTerm":0,"entries":[],"commit":0},"id":30}
DEBUG:root:sending {"dest": "n2", "src": "n5", "body": {"msg_id": 4, "in_reply_to": 12, "type": "AppendEntriesRes", "res": true, "term": 1, "next": 1, "commit": 0}}
DEBUG:root:received {"dest":"n5","src":"n2","body":{"msg_id":17,"type":"AppendEntries","term":1,"entries":[[["pass",null],0],[["write",[0,3]],1]],"prevIndex":0,"prevTerm":0,"commit":0},"id":42}
ERROR:root:fatal exception in handler
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab3/ms.py", line 27, in exitOnError
    fn(*args)
  File "/home/peter/Documents/tf/lab3/raft.py", line 353, in handle
    if len(log)-1<=msg.body.prevIndex+i and log[msg.body.prevIndex+i][1]!=msg.body.entries[i-1][1]:
IndexError: list index out of range
