DEBUG:root:received {"dest":"n3","body":{"type":"init","node_id":"n3","node_ids":["n0","n1","n2","n3"],"msg_id":1},"src":"c0","id":0}
INFO:root:node n3 initialized
DEBUG:root:sending {"dest": "c0", "src": "n3", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
DEBUG:root:received {"dest":"n3","src":"n1","body":{"msg_id":4,"type":"txnRep","msg":{"dest":"n1","body":{"txn":[["r",8,null],["r",9,null],["append",8,1]],"type":"txn","msg_id":1},"src":"c8","id":8},"originalid":1},"id":11}
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-3' coro=<handle() done, defined at /home/peter/Documents/tf/lab4/cent.py:57> exception=TypeError("trycommits() missing 1 required positional argument: 'db'")>
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab4/cent.py", line 83, in handle
    trycommits(msgQ)
TypeError: trycommits() missing 1 required positional argument: 'db'
DEBUG:root:received {"dest":"n3","src":"n2","body":{"msg_id":4,"type":"txnRep","msg":{"dest":"n2","body":{"txn":[["append",8,2],["r",9,null],["append",6,1],["r",9,null]],"type":"txn","msg_id":1},"src":"c9","id":12},"originalid":1},"id":15}
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-4' coro=<handle() done, defined at /home/peter/Documents/tf/lab4/cent.py:57> exception=TypeError("trycommits() missing 1 required positional argument: 'db'")>
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab4/cent.py", line 83, in handle
    trycommits(msgQ)
TypeError: trycommits() missing 1 required positional argument: 'db'
DEBUG:root:received {"dest":"n3","src":"n0","body":{"msg_id":4,"type":"txnRep","msg":{"dest":"n0","body":{"txn":[["r",9,null],["r",8,null],["append",8,3]],"type":"txn","msg_id":1},"src":"c10","id":16},"originalid":1},"id":19}
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-5' coro=<handle() done, defined at /home/peter/Documents/tf/lab4/cent.py:57> exception=TypeError("trycommits() missing 1 required positional argument: 'db'")>
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab4/cent.py", line 83, in handle
    trycommits(msgQ)
TypeError: trycommits() missing 1 required positional argument: 'db'
DEBUG:root:received {"dest":"n3","body":{"txn":[["r",9,null]],"type":"txn","msg_id":1},"src":"c11","id":20}
INFO:root:Sending msg to be replicated, destn0
DEBUG:root:sending {"dest": "n0", "src": "n3", "body": {"msg_id": 2, "type": "txnRep", "msg": {"dest": "n3", "body": {"txn": [["r", 9, null]], "type": "txn", "msg_id": 1}, "src": "c11", "id": 20}, "originalid": 1}}
INFO:root:Sending msg to be replicated, destn1
DEBUG:root:sending {"dest": "n1", "src": "n3", "body": {"msg_id": 3, "type": "txnRep", "msg": {"dest": "n3", "body": {"txn": [["r", 9, null]], "type": "txn", "msg_id": 1}, "src": "c11", "id": 20}, "originalid": 1}}
INFO:root:Sending msg to be replicated, destn2
DEBUG:root:sending {"dest": "n2", "src": "n3", "body": {"msg_id": 4, "type": "txnRep", "msg": {"dest": "n3", "body": {"txn": [["r", 9, null]], "type": "txn", "msg_id": 1}, "src": "c11", "id": 20}, "originalid": 1}}
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-6' coro=<handle() done, defined at /home/peter/Documents/tf/lab4/cent.py:57> exception=NameError("name 'ctx' is not defined")>
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab4/cent.py", line 76, in handle
    db.cleanup(ctx)
NameError: name 'ctx' is not defined
