DEBUG:root:received {"dest":"n1","body":{"type":"init","node_id":"n1","node_ids":["n1","n2","n3","n4","n5"],"msg_id":1},"src":"c3","id":3}
INFO:root:node n1 initialized
DEBUG:root:sending {"dest": "c3", "src": "n1", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
DEBUG:root:received {"dest":"n1","body":{"key":0,"type":"read","msg_id":1},"src":"c11","id":12}
DEBUG:root:sending {"dest": "c11", "src": "n1", "body": {"msg_id": 2, "in_reply_to": 1, "type": "error", "code": 20, "text": "Invalid Key"}}
DEBUG:root:received {"dest":"n1","body":{"key":0,"type":"read","msg_id":2},"src":"c11","id":18}
DEBUG:root:sending {"dest": "c11", "src": "n1", "body": {"msg_id": 3, "in_reply_to": 2, "type": "error", "code": 20, "text": "Invalid Key"}}
DEBUG:root:received {"dest":"n1","body":{"key":1,"value":2,"type":"write","msg_id":1},"src":"c17","id":26}
DEBUG:root:sending {"dest": "n2", "src": "n1", "body": {"msg_id": 4, "type": "AppendEntries", "term": 0, "prevIndex": 0, "prevTerm": 0, "entries": [["write", [1, 2], 0]], "commit": 0}}
DEBUG:root:sending {"dest": "n3", "src": "n1", "body": {"msg_id": 5, "type": "AppendEntries", "term": 0, "prevIndex": 0, "prevTerm": 0, "entries": [["write", [1, 2], 0]], "commit": 0}}
DEBUG:root:sending {"dest": "n4", "src": "n1", "body": {"msg_id": 6, "type": "AppendEntries", "term": 0, "prevIndex": 0, "prevTerm": 0, "entries": [["write", [1, 2], 0]], "commit": 0}}
DEBUG:root:sending {"dest": "n5", "src": "n1", "body": {"msg_id": 7, "type": "AppendEntries", "term": 0, "prevIndex": 0, "prevTerm": 0, "entries": [["write", [1, 2], 0]], "commit": 0}}
DEBUG:root:received {"dest":"n1","src":"n2","body":{"msg_id":4,"in_reply_to":4,"type":"AppendEntriesRes","res":true,"term":0,"next":1},"id":31}
DEBUG:root:received {"dest":"n1","src":"n3","body":{"msg_id":3,"in_reply_to":5,"type":"AppendEntriesRes","res":true,"term":0,"next":1},"id":32}
ERROR:root:fatal exception in handler
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab3/ms.py", line 27, in exitOnError
    fn(*args)
  File "/home/peter/Documents/tf/lab3/raft.py", line 316, in handle
    error_code = commit_command(log[maxn])
UnboundLocalError: local variable 'maxn' referenced before assignment
