DEBUG:root:received {"dest":"n5","body":{"type":"init","node_id":"n5","node_ids":["n1","n2","n3","n4","n5"],"msg_id":1},"src":"c2","id":2}
INFO:root:node n5 initialized
DEBUG:root:sending {"dest": "c2", "src": "n5", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
DEBUG:root:received {"dest":"n5","src":"n1","body":{"msg_id":5,"type":"AppendEntries","term":0,"prevIndex":0,"prevTerm":0,"entries":[[["pass",null],0]],"commit":0},"id":13}
DEBUG:root:sending {"dest": "n1", "src": "n5", "body": {"msg_id": 2, "in_reply_to": 5, "type": "AppendEntriesRes", "res": true, "term": 0, "next": 2, "commit": 0}}
DEBUG:root:received {"dest":"n5","body":{"key":1,"from":1,"to":4,"type":"cas","msg_id":1},"src":"c13","id":24}
DEBUG:root:sending {"dest": "c13", "src": "n5", "body": {"msg_id": 3, "in_reply_to": 1, "type": "error", "code": 11, "text": "Not Leader"}}
DEBUG:root:received {"dest":"n5","body":{"key":0,"from":4,"to":4,"type":"cas","msg_id":1},"src":"c14","id":26}
DEBUG:root:sending {"dest": "c14", "src": "n5", "body": {"msg_id": 4, "in_reply_to": 1, "type": "error", "code": 11, "text": "Not Leader"}}
DEBUG:root:received {"dest":"n5","src":"n1","body":{"msg_id":9,"type":"AppendEntries","term":0,"prevIndex":1,"prevTerm":[0,[0,1]],"entries":[["cas",[1,[2,0]],0]],"commit":0},"id":39}
DEBUG:root:sending {"dest": "n1", "src": "n5", "body": {"msg_id": 5, "in_reply_to": 9, "type": "AppendEntriesRes", "res": false, "term": 0}}
DEBUG:root:received {"dest":"n5","src":"n1","body":{"msg_id":13,"type":"AppendEntries","term":0,"prevIndex":0,"prevTerm":0,"entries":[["cas",[0,[0,1]],0],["cas",[1,[2,0]],0]],"commit":0},"id":47}
ERROR:root:fatal exception in handler
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab3/ms.py", line 27, in exitOnError
    fn(*args)
  File "/home/peter/Documents/tf/lab3/raft.py", line 326, in handle
    buildString([ "326",log,msg.body.prevIndex,commitIndex,node_id,command])
UnboundLocalError: local variable 'command' referenced before assignment
