DEBUG:root:received {"dest":"n5","body":{"type":"init","node_id":"n5","node_ids":["n1","n2","n3","n4","n5"],"msg_id":1},"src":"c4","id":4}
INFO:root:node n5 initialized
DEBUG:root:sending {"dest": "c4", "src": "n5", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
DEBUG:root:received {"dest":"n5","src":"n1","body":{"msg_id":5,"type":"AppendEntries","term":0,"prevIndex":0,"prevTerm":0,"entries":[[["pass",null],0]],"commit":0},"id":13}
DEBUG:root:sending {"dest": "n1", "src": "n5", "body": {"msg_id": 2, "in_reply_to": 5, "type": "AppendEntriesRes", "res": true, "term": 0, "next": 1, "commit": 0}}
DEBUG:root:received {"dest":"n5","body":{"key":1,"value":1,"type":"write","msg_id":1},"src":"c13","id":23}
DEBUG:root:sending {"dest": "c13", "src": "n5", "body": {"msg_id": 3, "in_reply_to": 1, "type": "error", "code": 11, "text": "Not Leader"}}
DEBUG:root:received {"dest":"n5","body":{"key":0,"from":3,"to":0,"type":"cas","msg_id":1},"src":"c14","id":25}
DEBUG:root:sending {"dest": "c14", "src": "n5", "body": {"msg_id": 4, "in_reply_to": 1, "type": "error", "code": 11, "text": "Not Leader"}}
DEBUG:root:received {"dest":"n5","body":{"key":1,"from":3,"to":2,"type":"cas","msg_id":1},"src":"c16","id":29}
DEBUG:root:sending {"dest": "c16", "src": "n5", "body": {"msg_id": 5, "in_reply_to": 1, "type": "error", "code": 11, "text": "Not Leader"}}
DEBUG:root:received {"dest":"n5","src":"n1","body":{"msg_id":10,"type":"AppendEntries","term":0,"prevIndex":1,"prevTerm":[1,[2,1]],"entries":[["cas",[1,[2,2]],0]],"commit":0},"id":37}
ERROR:root:fatal exception in handler
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab3/raft.py", line 278, in handle
    a = log[msg.body.prevIndex]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab3/ms.py", line 27, in exitOnError
    fn(*args)
  File "/home/peter/Documents/tf/lab3/raft.py", line 280, in handle
    buildString([ "280",log,msg.body.prevIndex,commitIndex,node_id])
  File "/home/peter/Documents/tf/lab3/raft.py", line 58, in buildString
    raise Exception(s)
Exception: 280
[(('pass', None), 0)]
1
0
n5

