DEBUG:root:received {"dest":"n4","body":{"type":"init","node_id":"n4","node_ids":["n1","n2","n3","n4","n5"],"msg_id":1},"src":"c2","id":2}
ERROR:root:fatal exception in handler
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab3/ms.py", line 27, in exitOnError
    fn(*args)
  File "/home/peter/Documents/tf/lab3/raft.py", line 186, in handle
    megaprint('init')
  File "/home/peter/Documents/tf/lab3/raft.py", line 54, in megaprint
    f.write("//////////////////////////////////")
NameError: name 'f' is not defined
