DEBUG:root:received {"dest":"n0","body":{"type":"init","node_id":"n0","node_ids":["n0","n1","n2","n3"],"msg_id":1},"src":"c3","id":3}
INFO:root:node n0 initialized
DEBUG:root:sending {"dest": "c3", "src": "n0", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
DEBUG:root:received {"dest":"n0","body":{"txn":[["r",8,null],["append",9,2]],"type":"txn","msg_id":1},"src":"c10","id":10}
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-3' coro=<handle() done, defined at /home/peter/Documents/tf/lab4/cent.py:57> exception=IndexError('list assignment index out of range')>
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab4/cent.py", line 71, in handle
    msgQ[msg.body.msg_id]= (msg,True)
IndexError: list assignment index out of range
