DEBUG:root:received {"dest":"n0","body":{"type":"init","node_id":"n0","node_ids":["n0","n1","n2","n3"],"msg_id":1},"src":"c3","id":3}
INFO:root:node n0 initialized
DEBUG:root:sending {"dest": "c3", "src": "n0", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
DEBUG:root:received {"dest":"n0","body":{"txn":[["append",8,1],["r",7,null]],"type":"txn","msg_id":1},"src":"c10","id":12}
INFO:root:executing txn
DEBUG:root:c10-1: locking 7
DEBUG:root:c10-1: locking 8
DEBUG:root:c10-1: appending to 8: 1
DEBUG:root:c10-1: reading 7
DEBUG:root:c10-1: updating 8: [1]
DEBUG:root:sending {"dest": "c10", "src": "n0", "body": {"msg_id": 2, "in_reply_to": 1, "type": "txn_ok", "txn": [["append", 8, 1], ["r", 7, null]]}}
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-3' coro=<handle() done, defined at /home/peter/Documents/tf/lab4/cent.py:13> exception=TypeError("'types.SimpleNamespace' object is not callable")>
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab4/cent.py", line 36, in handle
    msg(node, type='txnReplication',txn=msg.body.txn, originalid=msg.body.msg_id)
TypeError: 'types.SimpleNamespace' object is not callable
DEBUG:root:received {"dest":"n0","body":{"txn":[["append",8,2],["append",7,1]],"type":"txn","msg_id":2},"src":"c10","id":14}
INFO:root:executing txn
DEBUG:root:c10-2: locking 7
