DEBUG:root:received {"dest":"n1","body":{"type":"init","node_id":"n1","node_ids":["n1","n2","n3","n4","n5"],"msg_id":1},"src":"c3","id":3}
INFO:root:node n1 initialized
DEBUG:root:sending {"dest": "c3", "src": "n1", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
ERROR:root:fatal exception in handler
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab3/ms.py", line 27, in exitOnError
    fn(*args)
  File "/home/peter/Documents/tf/lab3/raft.py", line 170, in handle
    leader_alive_checker()
  File "/home/peter/Documents/tf/lab3/raft.py", line 98, in leader_alive_checker
    if not check_timestamp(leader_id):
  File "/home/peter/Documents/tf/lab3/raft.py", line 72, in check_timestamp
    return timeout_dict[node_id]-time.time_ns()<MAX_TIME_DIF
KeyError: None
