DEBUG:root:received {"dest":"n0","body":{"type":"init","node_id":"n0","node_ids":["n0","n1","n2","n3"],"msg_id":1},"src":"c3","id":3}
INFO:root:node n0 initialized
DEBUG:root:sending {"dest": "c3", "src": "n0", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
DEBUG:root:received {"dest":"n0","body":{"txn":[["r",9,null],["append",8,1],["r",8,null]],"type":"txn","msg_id":1},"src":"c9","id":10}
INFO:root:executing txn
DEBUG:root:c9-1: locking 8
DEBUG:root:c9-1: locking 9
INFO:root:CTX 
namespace(tid='c9-1', locked=[8, 9])
 msg id1
DEBUG:root:c9-1: reading 9
DEBUG:root:c9-1: appending to 8: 1
DEBUG:root:c9-1: reading 8
DEBUG:root:c9-1: updating 8: [1]
DEBUG:root:sending {"dest": "c9", "src": "n0", "body": {"msg_id": 2, "in_reply_to": 1, "type": "txn_ok", "txn": [["r", 9, null], ["append", 8, 1], ["r", 8, [1]]]}}
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-3' coro=<handle() done, defined at /home/peter/Documents/tf/lab4/cent.py:15> exception=TypeError("send() missing 1 required positional argument: 'dest'")>
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab4/cent.py", line 39, in handle
    send(node, type='txnRep',txn=msg.body.txn, originalid=msg.body.msg_id)
TypeError: send() missing 1 required positional argument: 'dest'
DEBUG:root:received {"dest":"n0","body":{"txn":[["r",9,null]],"type":"txn","msg_id":2},"src":"c9","id":12}
INFO:root:executing txn
DEBUG:root:c9-2: locking 9
