DEBUG:root:received {"dest":"n5","body":{"type":"init","node_id":"n5","node_ids":["n1","n2","n3","n4","n5"],"msg_id":1},"src":"c0","id":0}
INFO:root:node n5 initialized
DEBUG:root:sending {"dest": "c0", "src": "n5", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
DEBUG:root:received {"dest":"n5","src":"n1","body":{"msg_id":6,"type":"AppendEntries","term":0,"prevIndex":0,"prevTerm":0,"entries":[[["pass",null],0]],"commit":0},"id":14}
DEBUG:root:sending {"dest": "n1", "src": "n5", "body": {"msg_id": 2, "in_reply_to": 6, "type": "AppendEntriesRes", "res": true, "term": 0, "next": 2, "commit": 0}}
DEBUG:root:received {"dest":"n5","body":{"key":0,"from":0,"to":0,"type":"cas","msg_id":1},"src":"c10","id":20}
DEBUG:root:sending {"dest": "c10", "src": "n5", "body": {"msg_id": 3, "in_reply_to": 1, "type": "error", "code": 11, "text": "Not Leader"}}
DEBUG:root:received {"dest":"n5","src":"n1","body":{"msg_id":11,"type":"AppendEntries","term":0,"entries":[[["write",[0,2]],0]],"prevIndex":1,"prevTerm":0,"commit":0},"id":28}
DEBUG:root:sending {"dest": "n1", "src": "n5", "body": {"msg_id": 4, "in_reply_to": 11, "type": "AppendEntriesRes", "res": true, "term": 0, "next": 3, "commit": 0}}
DEBUG:root:received {"dest":"n5","src":"n1","body":{"msg_id":16,"type":"AppendEntries","term":0,"prevIndex":2,"prevTerm":0,"entries":[[["pass",null],0],[["pass",null],0],[["write",[0,2]],0]],"commit":0},"id":35}
ERROR:root:fatal exception in handler
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab3/ms.py", line 27, in exitOnError
    fn(*args)
  File "/home/peter/Documents/tf/lab3/raft.py", line 302, in handle
    if len(log)-1<=msg.body.prevIndex+i and log[msg.body.prevIndex+i][1]!=msg.body.entries[i-1][1]:
IndexError: list index out of range
