DEBUG:root:received {"dest":"n2","body":{"type":"init","node_id":"n2","node_ids":["n0","n1","n2","n3"],"msg_id":1},"src":"c1","id":1}
INFO:root:node n2 initialized
DEBUG:root:sending {"dest": "c1", "src": "n2", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
DEBUG:root:received {"dest":"n2","body":{"txn":[["r",7,null],["r",9,null]],"type":"txn","msg_id":1},"src":"c11","id":14}
INFO:root:executing txn
DEBUG:root:c11-1: locking 7
DEBUG:root:c11-1: locking 9
DEBUG:root:c11-1: reading 7
DEBUG:root:c11-1: reading 9
DEBUG:root:sending {"dest": "c11", "src": "n2", "body": {"msg_id": 2, "in_reply_to": 1, "type": "txn_ok", "txn": [["r", 7, null], ["r", 9, null]]}}
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-3' coro=<handle() done, defined at /home/peter/Documents/tf/lab4/cent.py:13> exception=TypeError("'types.SimpleNamespace' object is not callable")>
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab4/cent.py", line 36, in handle
    msg(node, type='txnReplication',txn=msg.body.txn, originalid=msg.body.msg_id)
TypeError: 'types.SimpleNamespace' object is not callable
DEBUG:root:received {"dest":"n2","body":{"txn":[["append",9,5]],"type":"txn","msg_id":2},"src":"c11","id":18}
INFO:root:executing txn
DEBUG:root:c11-2: locking 9
