DEBUG:root:received {"dest":"n4","body":{"type":"init","node_id":"n4","node_ids":["n1","n2","n3","n4","n5"],"msg_id":1},"src":"c0","id":0}
INFO:root:node n4 initialized
DEBUG:root:sending {"dest": "c0", "src": "n4", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
DEBUG:root:received {"dest":"n4","src":"n1","body":{"msg_id":4,"type":"AppendEntries","term":0,"prevIndex":0,"prevTerm":0,"entries":[[["pass",null],0]],"commit":0},"id":12}
DEBUG:root:sending {"dest": "n1", "src": "n4", "body": {"msg_id": 2, "in_reply_to": 4, "type": "AppendEntriesRes", "res": true, "term": 0, "next": 1, "commit": 0}}
DEBUG:root:received {"dest":"n4","body":{"key":1,"value":0,"type":"write","msg_id":1},"src":"c10","id":18}
DEBUG:root:sending {"dest": "c10", "src": "n4", "body": {"msg_id": 3, "in_reply_to": 1, "type": "error", "code": 11, "text": "Not Leader"}}
DEBUG:root:received {"dest":"n4","body":{"key":1,"from":1,"to":3,"type":"cas","msg_id":1},"src":"c12","id":22}
DEBUG:root:sending {"dest": "c12", "src": "n4", "body": {"msg_id": 4, "in_reply_to": 1, "type": "error", "code": 11, "text": "Not Leader"}}
DEBUG:root:received {"dest":"n4","src":"n1","body":{"msg_id":9,"type":"AppendEntries","term":0,"prevIndex":0,"prevTerm":0,"entries":[["cas",[1,[0,4]],0]],"commit":0},"id":29}
DEBUG:root:sending {"dest": "n1", "src": "n4", "body": {"msg_id": 5, "in_reply_to": 9, "type": "AppendEntriesRes", "res": true, "term": 0, "next": 1, "commit": 0}}
DEBUG:root:received {"dest":"n4","body":{"key":1,"from":0,"to":0,"type":"cas","msg_id":2},"src":"c12","id":39}
DEBUG:root:sending {"dest": "c12", "src": "n4", "body": {"msg_id": 6, "in_reply_to": 2, "type": "error", "code": 11, "text": "Not Leader"}}
DEBUG:root:received {"dest":"n4","src":"n1","body":{"msg_id":13,"type":"AppendEntries","term":0,"prevIndex":0,"prevTerm":0,"entries":[["cas",[1,[0,4]],0],["cas",[1,[4,4]],0]],"commit":0},"id":52}
ERROR:root:fatal exception in handler
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab3/raft.py", line 278, in handle
    a = log[msg.body.prevIndex]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab3/ms.py", line 27, in exitOnError
    fn(*args)
  File "/home/peter/Documents/tf/lab3/raft.py", line 280, in handle
    buildString([ "280",log,msg.body.prevIndex,commitIndex,node_id])
  File "/home/peter/Documents/tf/lab3/raft.py", line 58, in buildString
    raise Exception(s)
Exception: 280
[]
0
0
n4

