DEBUG:root:received {"dest":"n2","body":{"type":"init","node_id":"n2","node_ids":["n1","n2","n3","n4","n5"],"msg_id":1},"src":"c0","id":0}
INFO:root:node n2 initialized
DEBUG:root:sending {"dest": "c0", "src": "n2", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
DEBUG:root:received {"dest":"n2","body":{"key":0,"from":4,"to":1,"type":"cas","msg_id":1},"src":"c10","id":10}
DEBUG:root:sending {"dest": "c10", "src": "n2", "body": {"msg_id": 2, "in_reply_to": 1, "type": "error", "code": 11, "text": "Not Leader"}}
DEBUG:root:received {"dest":"n2","body":{"key":1,"from":4,"to":2,"type":"cas","msg_id":1},"src":"c12","id":14}
DEBUG:root:sending {"dest": "c12", "src": "n2", "body": {"msg_id": 3, "in_reply_to": 1, "type": "error", "code": 11, "text": "Not Leader"}}
DEBUG:root:received {"dest":"n2","src":"n1","body":{"msg_id":2,"type":"AppendEntries","term":0,"prevIndex":0,"prevTerm":0,"entries":[["write",[1,1],0]],"commit":0},"id":17}
DEBUG:root:sending {"dest": "n1", "src": "n2", "body": {"msg_id": 4, "in_reply_to": 2, "type": "AppendEntriesRes", "res": true, "term": 0, "next": 1, "commit": 0}}
DEBUG:root:received {"dest":"n2","body":{"key":0,"type":"read","msg_id":1},"src":"c15","id":27}
DEBUG:root:sending {"dest": "c15", "src": "n2", "body": {"msg_id": 5, "in_reply_to": 1, "type": "error", "code": 11, "text": "Not Leader"}}
DEBUG:root:received {"dest":"n2","src":"n1","body":{"msg_id":6,"type":"AppendEntries","term":0,"prevIndex":1,"prevTerm":[1,1],"entries":[["write",[0,4],0]],"commit":0},"id":34}
ERROR:root:fatal exception in handler
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab3/ms.py", line 27, in exitOnError
    fn(*args)
  File "/home/peter/Documents/tf/lab3/raft.py", line 264, in handle
    elif log[msg.body.prevIndex][1]!=msg.body.prevTerm:
IndexError: list index out of range
